[build]
  publish = "frontend"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "nodemailer", "pdf-parse"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
